In [1]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)
print("GPU Available:", tf.config.list_physical_devices('GPU'))


2025-06-20 18:26:09.417721: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-06-20 18:26:09.739392: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1750443969.865926      56 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1750443969.902642      56 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1750443970.167490      56 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking 

TensorFlow version: 2.19.0
GPU Available: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [2]:
 scalar = tf.constant(7)

I0000 00:00:1750443978.078074      56 gpu_device.cc:2019] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 2133 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3050 4GB Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6


In [3]:
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
print(scalar)

tf.Tensor(7, shape=(), dtype=int32)


In [5]:
scalar.ndim

0

In [6]:
vector = tf.constant([1,2])


In [7]:
vector


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [8]:
vector.ndim


1

In [9]:
vector_num = vector.numpy()

In [10]:
vector_num

array([1, 2], dtype=int32)

In [11]:
type(vector_num)

numpy.ndarray

In [12]:
type(vector)

tensorflow.python.framework.ops.EagerTensor

In [13]:
vector.ndim

1

In [14]:
matrix= tf.constant([[1,2],[3,4]])

In [15]:
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [16]:
matrix.ndim

2

In [17]:
matrix.shape

TensorShape([2, 2])

In [18]:
matrix1 = tf.constant([[[1,2,3],[4,5,6]]])

In [19]:
matrix1.ndim

3

In [20]:
matrix1.shape

TensorShape([1, 2, 3])

In [21]:
matrix2=tf.constant([1,1.,2])

In [22]:
matrix2

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 1., 2.], dtype=float32)>

In [23]:
print(matrix1[0])

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [24]:
print(matrix1[0].numpy())

[[1 2 3]
 [4 5 6]]


In [25]:
cb = tf.constant([1,0])

In [26]:
cb

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 0], dtype=int32)>

In [27]:
cb[0]=8

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [28]:
ucb = tf.Variable([2,4])


In [46]:
print(ucb)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([2, 4], dtype=int32)>


In [47]:
ucb[0].assign(90)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([90,  4], dtype=int32)>

In [48]:
ucb

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([90,  4], dtype=int32)>

In [49]:
print(ucb)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([90,  4], dtype=int32)>


In [30]:
a = tf.Variable([[1,2],[3,4]])
print(a)
a[0,0].assign(9)
print(a)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[9, 2],
       [3, 4]], dtype=int32)>


In [33]:
b = tf.Variable(7)
print(b)
b.assign(8)
print(b)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=7>
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=8>


In [37]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # create a NumPy array between 1 and 25
A = tf.Variable(numpy_A) # note: the shape total (2*4*3) has to match the number of elements in the array
numpy_A, A

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32),
 <tf.Variable 'Variable:0' shape=(24,) dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [38]:
random = tf.random.Generator.from_seed(42)

In [39]:
random

In [40]:
print(random)

In [41]:
type(random)

tensorflow.python.ops.stateful_random_ops.Generator

In [42]:
vec1 = random.normal(shape=(3,2))

In [43]:
vec1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [44]:
print(vec1)

tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193765 -1.8107855 ]], shape=(3, 2), dtype=float32)


In [45]:
random1 = tf.random.Generator.from_seed(42)
vec2 = random.normal(shape=(3,2))

In [46]:

print(vec2)

tf.Tensor(
[[ 0.17522676  0.71105534]
 [ 0.5488243   0.14896014]
 [-0.54757965  0.61634356]], shape=(3, 2), dtype=float32)


In [47]:
vec1==vec2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[False, False],
       [False, False],
       [False, False]])>

In [48]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set the seed for reproducibility
random_1 = random_1.normal(shape=(3, 2)) # create tensor from a normal distribution 
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

# Are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [49]:
print(random_1)

tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193765 -1.8107855 ]], shape=(3, 2), dtype=float32)


In [50]:
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [51]:
radomness = tf.random.Generator.from_seed(42)

In [52]:
newvec1 = radomness.normal(shape=(3,2))

In [53]:
newvec1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [54]:
radomness = tf.random.Generator.from_seed(42)

In [55]:
newvec2 = radomness.normal(shape=(3,2))

In [56]:
newvec2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [57]:
newvec1 == newvec2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

## SHUFFLING AND RANDOM SEED

In [58]:
not_shuff = tf.constant([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [59]:
not_shuff

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [60]:
tf.random.shuffle(not_shuff)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 4,  5,  6],
       [ 1,  2,  3],
       [ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [61]:
tf.random.shuffle(not_shuff)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [62]:
tf.random.shuffle(not_shuff)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 11, 12],
       [ 7,  8,  9]], dtype=int32)>

In [63]:
tf.random.shuffle(not_shuff)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [ 1,  2,  3]], dtype=int32)>

In [64]:
tf.random.shuffle(not_shuff)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 4,  5,  6],
       [ 1,  2,  3],
       [10, 11, 12],
       [ 7,  8,  9]], dtype=int32)>

In [65]:
tf.random.shuffle(not_shuff, seed= 42)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 7,  8,  9],
       [10, 11, 12],
       [ 4,  5,  6]], dtype=int32)>

In [66]:
tf.random.shuffle(not_shuff, seed= 42)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 4,  5,  6],
       [10, 11, 12],
       [ 7,  8,  9],
       [ 1,  2,  3]], dtype=int32)>

In [67]:
tf.random.shuffle(not_shuff, seed= 42)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 4,  5,  6],
       [ 7,  8,  9],
       [ 1,  2,  3],
       [10, 11, 12]], dtype=int32)>

In [68]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuff)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[10, 11, 12],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]], dtype=int32)>

In [69]:
ones = tf.ones(shape=[2,3,4,5], dtype= tf.int32)

In [70]:
ones

<tf.Tensor: shape=(2, 3, 4, 5), dtype=int32, numpy=
array([[[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]],


       [[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]]], dtype=int32)>

In [71]:
ones.shape

TensorShape([2, 3, 4, 5])

In [72]:
ones.ndim

4

In [73]:
rank_4_tensor = ones

In [74]:

# Get various attributes of tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (2*3*4*5):", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'int32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 5
Total number of elements (2*3*4*5): 120


In [75]:
ones.shape[0]

2

In [76]:
ones.shape[1]

3

In [77]:
print(tf.size(ones).numpy())

120


### Notes

1. to change multiply two tensors we use
tf.matmul(A,B)
2. to change datatype we use tf.cast(A, dtype = 'desired')
3. td.abs(A) ----> gives the absolute value of the 

Finding the min, max, mean, sum (aggregation)
You can quickly aggregate (perform a calculation on a whole tensor) tensors to find things like the minimum value, maximum value, mean and sum of all the elements.

To do so, aggregation methods typically have the syntax reduce()_[action], such as:

tf.reduce_min() - find the minimum value in a tensor.
tf.reduce_max() - find the maximum value in a tensor (helpful for when you want to find the highest prediction probability).
tf.reduce_mean() - find the mean of all elements in a tensor.
tf.reduce_sum() - find the sum of all elements in a tensor.
Note: typically, each of these is under the math module, e.g. tf.math.reduce_min() but you can use the alias tf.reduce_min().

In [81]:
C = tf.Variable([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

In [82]:
C

<tf.Variable 'Variable:0' shape=(3, 2, 3) dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]], dtype=int32)>

In [83]:
tf.transpose(C)

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 1, 1],
        [4, 4, 4]],

       [[2, 2, 2],
        [5, 5, 5]],

       [[3, 3, 3],
        [6, 6, 6]]], dtype=int32)>

In [84]:
my_list = [1,2,3,45,6]

In [88]:
# Create a list of indices
some_list = [0, 1, 2, 3]

# One hot encode them
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>